### ISSUE TITLE
Avoid `mkdir`

### ISSUE THREAD

**Issue by quinn-dougherty** [TheSpyder/rescript-mocha#3]
In `nix`, I can't build a rescript package that depends on `mocha`. 

```
> nashwires@0.0.1 build:rescript /build/nashwires
> rescript

Dependency on rescript-mocha
Fatal error: exception Unix.Unix_error(Unix.EACCES, "mkdir", "/build/nashwires/node_modules/rescript-mocha/lib")
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nashwires@0.0.1 build:rescript: `rescript`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the nashwires@0.0.1 build:rescript script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Is there a way I can avoid `mkdir`? Note this failure is at the stage of calling the `rescript` executable to build, not even running tests yet. 

With `nix` and flakes, you can reproduce by [cloning](https://github.com/quinn-dougherty/gtf/tree/70afaebb8e8578ab8fbafda2a5d088e0a3feaf4e) (checkout `70afaebb8e8578ab8fbafda2a5d088e0a3feaf4e`) and running `nix build .#nashwires`

**Comment by quinn-dougherty** [comment]
### Solved 
 ```nix
configurePhase = ''
          cp -r ${nodeDependencies}/lib/node_modules .
          export PATH="${nodeDependencies}/bin:$PATH"
          chmod -R +w node_modules
          mkdir -p node_modules/rescript-fast-check/lib
        '';
```

**Comment by TheSpyder** [comment]
This is a ReScript limitation, there's nothing I as a library author can do to work around it.
